name: Build
on:
  workflow_call:
    outputs:
      version:
        description: Built version
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2
      - name: Gradle Build
        run: ./gradlew build
      - name: Get Version
        id: version
        run: echo "version=$(./gradlew --console plain --quiet currentVersion -Prelease.quiet)" >> $GITHUB_OUTPUT
      - name: Upload build
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: build
          path: build/libs/*.jar
          retention-days: 7
          if-no-files-found: error
